# Basics
title: "Appu's blog"
baseURL: 'https://blog.appu.ltd/'
paginate: 10
languageCode: 'en-us'
theme:
  - "PaperMod"
  - "plausible-hugo"

# Build settings
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

