main:
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 10
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 20
  - identifier: example
    name: Archives
    url: /archives/
    weight: 30
  - identifier: web
    name: Main website
    url: https://apppu.ltd/
    weight: 30
